[firebase]
type = "service_account"
project_id = "budgettracker-bfe03"
private_key_id = "6b6a597bd0ea77d10f9eeefe237703f763767198"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCiPQacRhcyR3I4
Nm4RHMhRYngvJlkOgXwk9fylywESSpkIafhPmFPQj1DxNh6euR8Ihm+Atqxa59+F
KOF5FZUEY65zLckvxYeJ0epFMNlxA/NejfXiVgFDDLQWtPQNQIymf/Aq1MOZfZ68
ksZaaaWO4Q6WtngMR1M+MAqVqB9cGxJQz664uJfk4YntFJROin/BQiwFNLTaajF0
1MYPdiVkoCgFzzUs+YkNdh6YtA6yGJFi7VjO+MWZV/L8l030NDSeJ9mm0aULwvPw
LlluX88O4KEXdSl9OsYccYloQpd+t3+2m5EIgnsf8QvaKnztJq8X4fKD14e+wOEi
IhJ3X+cLAgMBAAECggEAKA0uu5emFFiE/xGY3IqhfU3045bw917J+gnsJDXYft6B
pw0aKvQtBNjMn6+/oWmMGrutfTYbmJmTmbj86LqGPj4pi++qsituiXyT/B7SH09d
XmNnZ0faKeZR8yUa9saPsm71KG28GAFmFaGabCmWoI443sYPHuDg0QJlKosFquPz
YwCH+QdLv9O4WBJfmc4BI958CCWUbBWF01UO95vpwlwQJy252yWMF+FA9TgqfGXe
vquJr8JttnRBvsOQGaT6CT+E7jjWPDJvBGrcdPauoVJyxWOZKUf/rD7oOPFDbVGH
HsL9LigfaLACOQ9SNJQSgHsgnEJrnAdjZyFjdP40WQKBgQDMDTVuR1QRszN1MTf1
fXreOX0i23wy/r2jmyUQI23d8LO8zMjtTsyowbvKjKnZJRBxoeh4GLqvxXp5u/wO
QjqeouPFDQR/8XRY3Ge2L1MRp38L6qN0OAsXsUfKmo9+f38qcPiNwXURdcy5kc27
dn2ilmOHxRDJ2SJXg/wckCInbQKBgQDLirJNlT5Il9+KedZDxLWlhQ3Wwbz98n3c
pqzHVSFmchtPXtfnLPek04fvR1/EyZSlSphr4th+h7Wo7TrzygJDDLnI6GHHXeyE
Boi1Ydeg6BWFKi/Mc+zANzD0BMGBrC6IH1v38ixSaGgXuIHLCbsFwalwLqTyK0Ga
NTatGIDlVwKBgFGKUbiw3kJ4du607WS3cPsOxBfC173VGFkhrUzmq4fOITUoLH7Q
R26EhJOrZFA2xHx0M96SG0AUTR4KZe4Yvy4Xb6eVzR+HkHPWF8ew36QlZ9qOOCVA
JAaivEqVOxRUxK9kF58mGK8SgO4C+tCXyBrJuBpQQKY4k8WfI4cSfeN9AoGAeEks
+iB6wFfQaXt7Hm1/k6O/++xejgziSKXPcbVjmbFRZmR8X0f5ydSgfs3FUPx39f7R
eOCEZLI6ruwTbMMy9wDsQkjij/l3rsZVwCtkTNka7qlxuffAMA/txCeTW9ivXw55
QVxCySiea3ZEbgMAHXTHd155aAwcJs/P0herBN0CgYAz4v71rJP3nqlDtKCeIUzw
bLZz0knHurTIktjhdBLm/dwN68Q9Y/Al7N0A1Pq614/6qfAEdd2z1uYBuwnbQS4k
sCCEfUn3dSOd6YT87w41IOBxLzWm4uyHu9bAcar9YEzPUkusFNQeTi+DGd6OPp7N
KJ5EeSuOeibWffhFDjACWQ==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-z4ul9@budgettracker-bfe03.iam.gserviceaccount.com"
client_id = "109992742271434971101"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-z4ul9%40budgettracker-bfe03.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

